### ISSUE TITLE
Evaluate how to integrate secret provisioning

### ISSUE THREAD

**Issue by nightkr** [stackabletech/listener-operator#79]
Ideally, most secrets would be associated with a listener bind, rather than with a pod or node.

We have a few different avenues that we could take for this...

# 1. Add an option for users to request "also give me this secret when mounting this listener"

- \+ Simpler UX for users (only one volume)
- \- Need to expose Secret-Op as an API to List-Op
- \- Makes list-op's node selection more complex

# 2. Add a secret volume scope for listeners

- \+ Secret key material doesn't pass through List-Op
- \+ Acknowledges that secrets and listeners have different lifecycles (for example: changing to autoTls makes pod scheduling more flexible, but shouldn't require all listeners to be deleted)
- \- There's no good way for Secret-Op to resolve a sibling listener, at best secret volume name => find PV => find PVC => find Listener
- \- The Listener API doesn't currently expose a way to resolve the actual NodePort IP (rather than a list of _potential_ IPs) from outside of the Pod volume

**Comment by dervoeti** [comment]
More details on this specific problem of solution number 2, after a quick discussion with @nightkr:
> The Listener API doesn't currently expose a way to resolve the actual NodePort IP (rather than a list of potential IPs) from outside of the Pod volume

The problem with using the `status.ingressAddresses` of the `Listener` is that it's an "external" view ("how clients should be configured to reach this listener"). We use `ingressAddresses` to generate the client configs/discovery maps, which may be deployed by e.g. admins outside of the k8s cluster, so we want to minimize changes to it as far as possible. That's why it is a list of all "potential" IPs of a Listener. We assume that clients will try them all until they're able to connect. So, `ingressAddresses` is not necessarily the same as the content of the PV. It can be wrong in both directions: it can include node IPs that don't lead to that Pod, or it can be missing IPs while waiting for the external load balancer to be provisioned. We could either live with that and add more IPs than necessary to the secret (and find a way to ensure all necessary IPs are present in the field), or we could add a new field to the `Listener` (like `listenerAddresses`) that reflects the contents of the PV (just the "real" IPs, not a list of "potential" IPs). It's probably also a good idea to add another status field, that indicates whether all IPs are present and the Listener is fully initialized (like `ready` = true/false).

This might help with the second problem of solution 2. If we find a good way to resolve a sibling listener from Secret-Op (should be possible), then we could go with this solution.

**Comment by dervoeti** [comment]
I think the steps for solution 2 would then be:

1. List-Op: Extend the `Listener` CRD with the new `status` fields
2. Secret-Op: Add "listener" as a `secrets.stackable.tech/scope`, find the sibling `Listener` and get the IPs from its `status`

**Comment by siegfriedweber** [comment]
# Motivation

The secret-operator currently provides the following back-ends:
- `autoTls`
- `k8sSearch`
- `kerberosKeytab`

`autoTls` uses scopes to populate the claims (such as `subjectAlternateName`) of the provisioned certificates. If a Listener is used to expose a service then the claims should contain the addresses provided by the Listener. Otherwise, if the Listener would advertise an address which is not contained in the `subjectAlternateName` then the certificate would be considered as invalid.

`k8sSearch` selects a Secret based on the scopes. There is already a Service scope. A Service name can be set in the scope, e.g. `secrets.stackable.tech/scope: service=my-service`, and if a Secret is labeled with `secrets.stackable.tech/service: my-service`, then it is chosen. According to [the comment in the code](https://github.com/stackabletech/secret-operator/blob/23.7.0/rust/operator-binary/src/backend/mod.rs#L38), the given Service is "A Kubernetes `Service` that the pod is participating in", but this is not checked and even nonexistent service names work. However, a Pod does not know if a Service references it, so the Service could be used to allow Pods accessing a Secret. A Listener scope would probably be used the same way. In contrast to a Service, a Pod defines/requests a Listener and therefore it is not clear what the purpose of this scope would be.

**TODO:** Clarify if a Listener scope for `k8sSearch` makes sense.

`kerberosKeytab` uses scopes to set the service principals in a keytab. The DNS addresses of the Node, Pod, or Service are used, IP addresses are not. A Listener only contains IP adresses, so this scope does probably not make sense with this back-end.

**TODO:** Clarify if a Listener scope for `kerberosKeytab` makes sense anyway.

# Implementation questions

A Pod can mount several Listeners volumes. Therefore all solutions must take into account that there is not only the one (sibling) Listener but a whole set of Listeners.

So the next question is, how to define the Listener scope. Pod and Node scopes are defined without a name argument (`secrets.stackable.tech/scope: pod,node`) because there is only one binding and the names are not necessarily known beforehand, whereas a Service scope needs the name of the Service (`secrets.stackable.tech/scope: service=my-service`). If a Listener is created manually and specified with the annotation `listeners.stackable.tech/listener-name` on the PersistentVolumeClaim then `secrets.stackable.tech/scope: listener=my-listener` could make sense. If instead a ListenerClass is specified and a new Listener is provisioned then `secrets.stackable.tech/scope: listeners` (plural) could be the choice.

**TODO:** Clarify how the Listener scope should be defined.

> There's no good way for Secret-Op to resolve a sibling listener, at best secret volume name => find PV => find PVC => find Listener

Is this path viable?
Secret PVC ⇒ Pod via ownerReferences ⇒ Listener via labels

```yaml
---
kind: PersistentVolumeClaim
metadata:
  name: nginx-bccb6f98f-fb66f-tls
  annotations:
    secrets.stackable.tech/class: tls
  ownerReferences:
  - kind: Pod
    name: nginx-bccb6f98f-fb66f
    uid: 67871791-2f83-4a3e-abc8-df1d5f523648
---
kind: Pod
metadata:
  name: nginx-bccb6f98f-fb66f
  uid: 67871791-2f83-4a3e-abc8-df1d5f523648
  labels:
    listeners.stackable.tech/mounted-listener.nginx-bccb6f98f-fb66f-listener: "true"
---
kind: Listener
metadata:
  name: nginx-bccb6f98f-fb66f-listener
```

> The Listener API doesn't currently expose a way to resolve the actual NodePort IP (rather than a list of potential IPs) from outside of the Pod volume

Together with [the comment from @dervoeti](https://github.com/stackabletech/listener-operator/issues/79#issuecomment-1630541632) this sounds reasonable but I could not reproduce these situations in my test cluster. A reproduction would help to understand the problem entirely. The status of the Listener and the volume are populated by the same (or at least equal) code. Then how can it differ so much?

**TODO:** Try to understand the problem again.

> It's probably also a good idea to add another status field, that indicates whether all IPs are present and the Listener is fully initialized (like ready = true/false).

Is the Listener volume populated once and then it is seen as ready or can changes still happen and it cannot be known when it reached its final state?

If the Listener is "ready" when the volume is mounted **and** if the mentioned search path with the `mounted-listener` label can be used then the found Listener is mounted and therefore ready.

**TODO:** Try to understand what ready means.

**Comment by nightkr** [comment]
> TODO: Clarify if a Listener scope for k8sSearch makes sense.
Yes, we need to support preprovisioning for all secret types. This is largely a policy question.

> TODO: Clarify if a Listener scope for kerberosKeytab makes sense anyway.
The krb principal would be provisioned for whatever hostname the client uses to connect. So if the listener has a hostname of some kind then that, otherwise the IP address.

> Is this path viable?
> Secret PVC ⇒ Pod via ownerReferences ⇒ Listener via labels

Sadly not quite, since the listener set can change over time, while the secrets must (currently) all be known at pod startup.

For example, a use case that we'd probably want to support at some point is dynamic role-based listeners (primary/follower), so that a writer can connect straight to the primary. We'd still want the follower to have primary credentials so that it is ready to take over in case it gets elected, but it wouldn't be selected as an endpoint yet for the listener.

> Together with https://github.com/stackabletech/listener-operator/issues/79#issuecomment-1630541632 this sounds reasonable but I could not reproduce these situations in my test cluster. The ingressAddresses in the Listener and the mounted volume were always the same. For instance, if a LoadBalancer did not assign an address, then the Pod stayed in the Init phase and the ingressAddresses were empty. A NodePort Listener always only contained the Node where the Pod was deployed. A reproduction would help to understand the problem entirely. The status of the Listener and the volume are populated by the same (or at least equal) code. Then how can it differ so much?

One way to repro this one is bind multiple pods to the same nodeport listener (see https://github.com/stackabletech/listener-operator/blob/fa109b8e2d76e3b4dfa71e01aeb28c74fe391e21/examples/nginx-preprovisioned-lb.yaml but increase the number of replicas and use a nodeport listenerclass). `.ingressAddresses` should contain all nodes running nginx pods, while `/usr/share/nginx/html/listener/addresses` should only contain the node that *that* pod is running on.

**Comment by siegfriedweber** [comment]
The insights from these comments, conversations, and manual tests were used to create a follow-up ticket: #95
